### ISSUE TITLE
Dockerfile question

### ISSUE THREAD

**Issue by ghost** [eldada/jenkins-pipeline-kubernetes#3]
Dockerfile 的COPY指令中拷贝的本地文件为什么是site
 FROM nginx:1.15.8                                                                         2
 LABEL Author "eldada@jfrog.com"
COPY site /usr/share/nginx/html

**Comment by eldada** [comment]
Sorry - don't know chines. What is the problem here?

**Comment by ghost** [comment]
sorry,because I see this repos in china blog
my question is in Dockerfile,ADD site /usr/share/nginx/html,but I do not understand "site" means

**Comment by eldada** [comment]
I'm honoured to be in a chines blog!
The command `COPY site /usr/share/nginx/html` means copying the current **directory** `site` into the Docker image under the `/usr/share/nginx/html` directory.
The `site` directory is created at build time and contains the static html, images and css code that's under the `src` directory now.

See in the [build.sh](https://github.com/eldada/jenkins-pipeline-kubernetes/blob/master/build.sh#L66) the `buildDockerImage()` function that creates this directory for the Docker image build.

**Comment by ghost** [comment]
Thank you, I already understand it.
